apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:

      initContainers:
        - name: airflow-init
          image: srinivasa594/my-app:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db migrate && \
              airflow users create \
                --username admin \
                --password admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com || true

      # ✅ MAIN CONTAINER
      containers:
        - name: my-app
          image: srinivasa594/my-app:latest
          imagePullPolicy: Always

          command: ["airflow", "webserver"]

          ports:
            - containerPort: 8080