apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      volumes:
        - name: airflow-data
          persistentVolumeClaim:
            claimName: airflow-pvc
        - name: dags
          emptyDir: {}
      initContainers:
        - name: airflow-init
          image: srinivasa594/my-app:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db init &&
              airflow users create \
                --username admin \
                --password admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com || true
          env:
            - name: AIRFLOW_HOME
              value: /opt/airflow
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN   # 🔥 ADD THIS
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          volumeMounts:
            - name: airflow-data
              mountPath: /opt/airflow
      containers:
        - name: scheduler
          image: srinivasa594/my-app:latest
          command: ["airflow", "scheduler"]
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW_HOME
              value: /opt/airflow
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /opt/airflow/dags/repo/dags
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          volumeMounts:
            - name: airflow-data
              mountPath: /opt/airflow
            - name: dags
              mountPath: /opt/airflow/dags
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          env:
            - name: GITSYNC_REPO
              value: "https://github.com/srirama9908-lang/SnowflakeDbt_Airflow-docker-Deploy_Ott.git"
            - name: GITSYNC_REF
              value: "master"
            - name: GITSYNC_ROOT
              value: "/git"
            - name: GITSYNC_LINK
              value: "repo"
            - name: GITSYNC_PERIOD
              value: "60s"
          volumeMounts:
            - name: dags
              mountPath: /git